Performance property
Freshly/Behave pull request #32
Opened 2021-04-16 19:23 UTC by bytedissident

Add performance testing a test run by default and controller by a property.

2021-05-29 23:34 UTC, Vadimkomis requested changes

2021-05-29 23:34 UTC, Vadimkomis commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>              api.scrollTableTo(indexPath: indexPath, identfier: self.performanceView)
Typo. Let's fix it.

2021-05-29 23:34 UTC, Vadimkomis commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>          navgateToThePerformanceScreen(api)
Spelling mistake. Let's fix it.

2021-05-29 23:34 UTC, Vadimkomis commented on README.md
> +To make your test run use the run method. Behave tests will not run without explicitly calling run. Run has: **success**, **fail** and **warn** completion handlers.
One suggestion about the readme, is to make it easier for navigation. For example, I like how `Alamofire` has: https://github.com/Alamofire/Alamofire/blob/master/README.md

2021-05-29 23:34 UTC, Vadimkomis commented on Example/ExampleAppTests/PerformanceBDDTests.swift
> +    func testPerformance_isInEfficientWithPropertyOff() {
Can you clarify what do you mean by "property is broken" ?

2021-05-30 02:17 UTC, bytedissident commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>          navgateToThePerformanceScreen(api)
what's the mistake?

2021-05-30 02:18 UTC, bytedissident commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>          navgateToThePerformanceScreen(api)
👍

2021-05-30 02:20 UTC, bytedissident commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>              api.scrollTableTo(indexPath: indexPath, identfier: self.performanceView)
What's the typo?

2021-05-30 02:22 UTC, bytedissident commented on README.md
> +To make your test run use the run method. Behave tests will not run without explicitly calling run. Run has: **success**, **fail** and **warn** completion handlers.
I like that too, lets do it as a separate PR so I can think about it. I'll add an issue.

2021-05-30 02:23 UTC, bytedissident commented on README.md
> +To make your test run use the run method. Behave tests will not run without explicitly calling run. Run has: **success**, **fail** and **warn** completion handlers.
https://github.com/Freshly/Behave/issues/41

2021-05-30 02:25 UTC, bytedissident commented on Example/ExampleAppTests/PerformanceBDDTests.swift
> +    func testPerformance_isInEfficientWithPropertyOff() {
Updated, changed language.

2021-05-30 23:08 UTC, Vadimkomis commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>          navgateToThePerformanceScreen(api)
`navgateToThePerformanceScreen` should be `navigateToThePerformanceScreen`

2021-05-30 23:08 UTC, Vadimkomis commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>              api.scrollTableTo(indexPath: indexPath, identfier: self.performanceView)
`identfier` should be `identifier`

2021-05-31 11:16 UTC, bytedissident commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>              api.scrollTableTo(indexPath: indexPath, identfier: self.performanceView)
👍

2021-05-31 11:16 UTC, bytedissident commented on Example/ExampleAppTests/PerformanceBDDTests.swift
>          navgateToThePerformanceScreen(api)
👍

2021-06-01 17:43 UTC, Vadimkomis approved these changes
Very nice pr

2021-06-01 17:43 UTC, merged